# Generated by Django 4.2.6 on 2024-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
