# Generated by Django 4.2.6 on 2024-03-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkApi', '0002_rename_user_id_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
