# Generated by Django 4.2.6 on 2024-03-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkApi', '0004_rename_branch_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='branch_name',
            new_name='cohort_name',
        ),
    ]
