# Generated by Django 4.2.6 on 2024-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkApi', '0006_school_rename_branch_studentprofile_cohort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.AddField(
            model_name='subject',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
