# Generated by Django 4.2.6 on 2024-03-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkApi', '0007_remove_studentprofile_school_subject_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='days_required',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='extend_days',
        ),
    ]
