from django.contrib import admin
from .models import *

admin.site.register(CustomUser)
admin.site.register(Course)
admin.site.register(Subject)
admin.site.register(Chapter)
admin.site.register(Cohort)
admin.site.register(SecretKey)
admin.site.register(AdminProfile)
admin.site.register(TeacherProfile)
admin.site.register(StudentProfile)
admin.site.register(School)
admin.site.register(Attendance)
admin.site.register(AttendanceReport)
admin.site.register(LeaveReportStudent)
admin.site.register(LeaveReportTeacher)
admin.site.register(FeedBackStudent)
admin.site.register(FeedBackTeacher)
admin.site.register(NotificationTeacher)
